import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { model_tracker_pages } from "./model-tracker.pages.ts";
import { model_tracker_tables } from "./model-tracker.tables.ts";

export const model_tracker_module = define_module({
  resource: "model-tracker",
  labels: {
    singular: "Rastreador/Catálogo de modelos Mongo",
    plural: "Rastreador/Catálogo de modelos Mongo",
    read: "Ver Rastreador/Catálogo de modelos Mongo",
    write: "Editar Rastreador/Catálogo de modelos Mongo",
  },
  routes: define_crud({
    resource: "model-tracker",
    table: "model_tracker",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "model-tr",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      __model_name: { type: "string", search: true },
      __collection: { type: "string", search: true },
      __use_text_search: { type: "boolean" },
      __text_index_paths: { type: "json" },
      __text_index_populate_options: { type: "json" },
      __field_paths: { type: "json" },
      __fingerprint: { type: "string", search: true },
      __schema_fields: { type: "json" },
      __state_fields: { type: "string", search: true },
      __batch_matchable_fields: { type: "json" },
      __use_history_recollection: { type: "boolean" },
      __history_path_names: { type: "json" },
      __ref: { type: "string", search: true },
      __strict: { type: "boolean" },
      __strictQuery: { type: "boolean" },
      __bufferCommands: { type: "boolean" },
      __capped: { type: "boolean" },
      __versionKey: { type: "string", search: true },
      __optimisticConcurrency: { type: "boolean" },
      __minimize: { type: "boolean" },
      __autoIndex: { type: "json" },
      __discriminatorKey: { type: "string", search: true },
      __shardKey: { type: "json" },
      __read: { type: "json" },
      __validateBeforeSave: { type: "boolean" },
      __validateModifiedOnly: { type: "boolean" },
      ___id: { type: "boolean" },
      __id: { type: "boolean" },
      __typeKey: { type: "string", search: true },
      __timestamps: { type: "boolean" },
      __pluralization: { type: "boolean" },
      path: { type: "string", search: true },
      type: { type: "string", search: true },
      is_array: { type: "boolean" },
      is_reference: { type: "boolean" },
      label: { type: "string", search: true },
      source: { type: "string", search: true },
      value: { type: "string", search: true },
      display_leyend: { type: "string", search: true },
      color: { type: "string", search: true },
      icon: { type: "string", search: true },
      field_name: { type: "string", search: true },
      enabled: { type: "boolean" },
      read_only: { type: "boolean" },
      values: { type: "json" },
      fields: { type: "json" },
      has_state_fields: { type: "boolean" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: model_tracker_tables,
  pages: model_tracker_pages,
  menu: [],
});
