import {
  build_feature_shell_page,
  type KirletPageDecl,
} from "@opus-perpetuus/imperium-core-kit";

const API = "api://m/subject-configuracion";

export const model_tracker_pages: KirletPageDecl[] = [
  {
    id: "configuracion.model-tracker",
    path: "model-tracker",
    permission: "subject.configuracion.model-tracker.read",
    build: () =>
      build_feature_shell_page({
        id: "configuracion.model-tracker",
        owner: "subject-configuracion",
        title: "Rastreador/Catálogo de modelos Mongo",
        props: {
          basePath: "model-tracker",
          idKey: "id",
          nameKey: "name",
          view: {
            title: "Rastreador/Catálogo de modelos Mongo",
            subtitle: "Submenú de configuracion",
            pluralLabel: "rastreador/catálogo de modelos mongo",
            singularLabel: "rastreador/catálogo de modelos mongo",
            emptyTitle: "Sin registros",
            emptyDescription: "Migra desde Mongo o crea el primero",
          },
          data: {
            list: `${API}/model-tracker`,
            record: `${API}/model-tracker/:id`,
            create: { method: "POST", action: `${API}/model-tracker` },
            update: { method: "PATCH", action: `${API}/model-tracker/:id` },
            delete: { method: "DELETE", action: `${API}/model-tracker/:id` },
          },
          table: {
            columns: [
              { key: "name", label: "Nombre", sortable: true, priority: 1 },
              { key: "is_active", label: "Activo", sortable: true, priority: 2 },
              { key: "ref", label: "Ref", sortable: true, priority: 3 },
              { key: "__model_name", label: "  model name", sortable: true, priority: 3 },
              { key: "__collection", label: "  collection", sortable: true, priority: 3 },
              { key: "__use_text_search", label: "  use text search", sortable: true, priority: 3 },
              { key: "__text_index_paths", label: "  text index paths", sortable: true, priority: 3 },
              { key: "__text_index_populate_options", label: "  text index populate options", sortable: true, priority: 3 },
              { key: "__field_paths", label: "  field paths", sortable: true, priority: 3 },
            ],
            fillHeight: true,
            serverQuery: true,
          },
          form: {
            fields: [
              { name: "name", component: "input-text", label: "Nombre", required: true },
              { name: "description", component: "input-text", label: "Descripción" },
              { name: "ref", component: "input-text", label: "Referencia (_ref)" },
              { name: "__model_name", component: "input-text", label: "  model name" },
              { name: "__collection", component: "input-text", label: "  collection" },
              { name: "__use_text_search", component: "input-checkbox", label: "  use text search" },
              { name: "__text_index_paths", component: "input-json", label: "  text index paths" },
              { name: "__text_index_populate_options", component: "input-json", label: "  text index populate options" },
              { name: "__field_paths", component: "input-json", label: "  field paths" },
              { name: "__fingerprint", component: "input-text", label: "  fingerprint" },
              { name: "__schema_fields", component: "input-json", label: "  schema fields" },
              { name: "__state_fields", component: "input-text", label: "  state fields" },
              { name: "__batch_matchable_fields", component: "input-json", label: "  batch matchable fields" },
              { name: "__use_history_recollection", component: "input-checkbox", label: "  use history recollection" },
              { name: "__history_path_names", component: "input-json", label: "  history path names" },
              { name: "__ref", component: "input-text", label: "  ref" },
              { name: "__strict", component: "input-checkbox", label: "  strict" },
              { name: "__strictQuery", component: "input-checkbox", label: "  strictQuery" },
              { name: "__bufferCommands", component: "input-checkbox", label: "  bufferCommands" },
              { name: "__capped", component: "input-checkbox", label: "  capped" },
              { name: "__versionKey", component: "input-text", label: "  versionKey" },
              { name: "__optimisticConcurrency", component: "input-checkbox", label: "  optimisticConcurrency" },
              { name: "__minimize", component: "input-checkbox", label: "  minimize" },
              { name: "__autoIndex", component: "input-json", label: "  autoIndex" },
              { name: "__discriminatorKey", component: "input-text", label: "  discriminatorKey" },
              { name: "__shardKey", component: "input-json", label: "  shardKey" },
              { name: "__read", component: "input-json", label: "  read" },
              { name: "__validateBeforeSave", component: "input-checkbox", label: "  validateBeforeSave" },
              { name: "__validateModifiedOnly", component: "input-checkbox", label: "  validateModifiedOnly" },
              { name: "___id", component: "input-checkbox", label: "   id" },
              { name: "__id", component: "input-checkbox", label: "  id" },
              { name: "__typeKey", component: "input-text", label: "  typeKey" },
              { name: "__timestamps", component: "input-checkbox", label: "  timestamps" },
              { name: "__pluralization", component: "input-checkbox", label: "  pluralization" },
              { name: "path", component: "input-text", label: "path" },
              { name: "type", component: "input-text", label: "type" },
              { name: "is_array", component: "input-checkbox", label: "is array" },
              { name: "is_reference", component: "input-checkbox", label: "is reference" },
              { name: "label", component: "input-text", label: "label" },
              { name: "source", component: "input-text", label: "source" },
              { name: "value", component: "input-text", label: "value" },
              { name: "display_leyend", component: "input-text", label: "display leyend" },
              { name: "color", component: "input-text", label: "color" },
              { name: "icon", component: "input-text", label: "icon" },
              { name: "field_name", component: "input-text", label: "field name" },
              { name: "enabled", component: "input-checkbox", label: "enabled" },
              { name: "read_only", component: "input-checkbox", label: "read only" },
              { name: "values", component: "input-json", label: "values" },
              { name: "fields", component: "input-json", label: "fields" },
              { name: "has_state_fields", component: "input-checkbox", label: "has state fields" },
            ],
          },
        },
      }),
  },
];
