import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const model_tracker_tables: KirletTableDecl[] = [
  {
    name: "model_tracker",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "__model_name", type: "text" },
      { name: "__collection", type: "text" },
      { name: "__use_text_search", type: "boolean" },
      { name: "__text_index_paths", type: "json" },
      { name: "__text_index_populate_options", type: "json" },
      { name: "__field_paths", type: "json" },
      { name: "__fingerprint", type: "text" },
      { name: "__schema_fields", type: "json" },
      { name: "__state_fields", type: "text" },
      { name: "__batch_matchable_fields", type: "json" },
      { name: "__use_history_recollection", type: "boolean" },
      { name: "__history_path_names", type: "json" },
      { name: "__ref", type: "text" },
      { name: "__strict", type: "boolean" },
      { name: "__strictQuery", type: "boolean" },
      { name: "__bufferCommands", type: "boolean" },
      { name: "__capped", type: "boolean" },
      { name: "__versionKey", type: "text" },
      { name: "__optimisticConcurrency", type: "boolean" },
      { name: "__minimize", type: "boolean" },
      { name: "__autoIndex", type: "json" },
      { name: "__discriminatorKey", type: "text" },
      { name: "__shardKey", type: "json" },
      { name: "__read", type: "json" },
      { name: "__validateBeforeSave", type: "boolean" },
      { name: "__validateModifiedOnly", type: "boolean" },
      { name: "___id", type: "boolean" },
      { name: "__id", type: "boolean" },
      { name: "__typeKey", type: "text" },
      { name: "__timestamps", type: "boolean" },
      { name: "__pluralization", type: "boolean" },
      { name: "path", type: "text" },
      { name: "type", type: "text" },
      { name: "is_array", type: "boolean" },
      { name: "is_reference", type: "boolean" },
      { name: "label", type: "text" },
      { name: "source", type: "text" },
      { name: "value", type: "text" },
      { name: "display_leyend", type: "text" },
      { name: "color", type: "text" },
      { name: "icon", type: "text" },
      { name: "field_name", type: "text" },
      { name: "enabled", type: "boolean" },
      { name: "read_only", type: "boolean" },
      { name: "values", type: "json" },
      { name: "fields", type: "json" },
      { name: "has_state_fields", type: "boolean" },
    ],
    indexes: [
      { name: "idx_model_tracker_name", columns: ["name"] },
      { name: "idx_model_tracker_active", columns: ["is_active"] },
    ],
  },
];
