import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { attachment_management_pages } from "./attachment-management.pages.ts";
import { attachment_management_tables } from "./attachment-management.tables.ts";

export const attachment_management_module = define_module({
  resource: "attachment-management",
  labels: {
    singular: "Documentos y adjuntos",
    plural: "Documentos y adjuntos",
    read: "Ver Documentos y adjuntos",
    write: "Editar Documentos y adjuntos",
  },
  routes: define_crud({
    resource: "attachment-management",
    table: "attachment_management",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "attachme",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      name_stored: { type: "string", search: true },
      mimetype: { type: "string", search: true },
      created_by_id: { type: "string", search: true },
      related_model: { type: "string", search: true },
      related_record_id: { type: "string", search: true },
      field: { type: "string", search: true },
      size_in_kb: { type: "string", search: true },
      file_ext: { type: "string", search: true },
      index_if_is_array: { type: "string", search: true },
      inside_array: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: attachment_management_tables,
  pages: attachment_management_pages,
  menu: [
    {
      id: "configuracion.attachment-management",
      label: "Documentos y adjuntos",
      order: 0,
      pageId: "configuracion.attachment-management",
      path: "attachment-management",
      permission: "subject.configuracion.attachment-management.read",
      icon: "document",
    },
    {
      id: "configuracion.user",
      label: "Usuarios",
      order: 0,
      pageId: "configuracion.user",
      path: "user",
      permission: "subject.configuracion.user.read",
      icon: "document",
    },
    {
      id: "configuracion.user-group",
      label: "Grupos de usuario",
      order: 0,
      pageId: "configuracion.user-group",
      path: "user-group",
      permission: "subject.configuracion.user-group.read",
      icon: "document",
    },
    {
      id: "configuracion.zpl-management",
      label: "Impresoras Zebra",
      order: 0,
      pageId: "configuracion.zpl-management",
      path: "zpl-management",
      permission: "subject.configuracion.zpl-management.read",
      icon: "document",
    },
    {
      id: "configuracion.country",
      label: "Paises",
      order: 0,
      pageId: "configuracion.country",
      path: "country",
      permission: "subject.configuracion.country.read",
      icon: "document",
    },
    {
      id: "configuracion.record-rules",
      label: "Reglas de registro",
      order: 0,
      pageId: "configuracion.record-rules",
      path: "record-rules",
      permission: "subject.configuracion.record-rules.read",
      icon: "document",
    },
    {
      id: "configuracion.menu-management",
      label: "Manejo de menús",
      order: 0,
      pageId: "configuracion.menu-management",
      path: "menu-management",
      permission: "subject.configuracion.menu-management.read",
      icon: "document",
    },
    {
      id: "configuracion.configuration",
      label: "Parametros del sistema",
      order: 0,
      pageId: "configuracion.configuration",
      path: "configuration",
      permission: "subject.configuracion.configuration.read",
      icon: "document",
      children: [
        {
          id: "configuracion.interface-restriction",
          label: "Restricciones de interfaz",
          order: 1,
          pageId: "configuracion.interface-restriction",
          path: "interface-restriction",
          permission: "subject.configuracion.interface-restriction.read",
          icon: "document",
        }
      ],
    },
    {
      id: "configuracion.access-rights",
      label: "Permisos de acceso",
      order: 0,
      pageId: "configuracion.access-rights",
      path: "access-rights",
      permission: "subject.configuracion.access-rights.read",
      icon: "document",
    },
    {
      id: "configuracion.module-management",
      label: "Módulos",
      order: 0,
      pageId: "configuracion.module-management",
      path: "module-management",
      permission: "subject.configuracion.module-management.read",
      icon: "document",
    },
    {
      id: "configuracion.status-option-control",
      label: "Opciones de estatus",
      order: 0,
      pageId: "configuracion.status-option-control",
      path: "status-option-control",
      permission: "subject.configuracion.status-option-control.read",
      icon: "document",
    },
    {
      id: "configuracion.custom-field-control",
      label: "Campos personalizados",
      order: 0,
      pageId: "configuracion.custom-field-control",
      path: "custom-field-control",
      permission: "subject.configuracion.custom-field-control.read",
      icon: "document",
    },
    {
      id: "configuracion.folder.auto-increment-control-menu-serials-root",
      label: "Configuración de seriales",
      order: 0,
      children: [
        {
          id: "configuracion.auto-increment-control",
          label: "Configuración de counters",
          order: 0,
          pageId: "configuracion.auto-increment-control",
          path: "auto-increment-control",
          permission: "subject.configuracion.auto-increment-control.read",
          icon: "document",
        },
        {
          id: "configuracion.custom-pattern-increment-sequence-parts",
          label: "Partes de secuencia",
          order: 1,
          pageId: "configuracion.custom-pattern-increment-sequence-parts",
          path: "custom-pattern-increment-sequence-parts",
          permission: "subject.configuracion.custom-pattern-increment-sequence-parts.read",
          icon: "document",
        },
        {
          id: "configuracion.custom-pattern-condition",
          label: "Custom pattern",
          order: 2,
          pageId: "configuracion.custom-pattern-condition",
          path: "custom-pattern-condition",
          permission: "subject.configuracion.custom-pattern-condition.read",
          icon: "document",
        }
      ],
    },
    {
      id: "configuracion.branchoffice",
      label: "Sucursales",
      order: 0,
      pageId: "configuracion.branchoffice",
      path: "branchoffice",
      permission: "subject.configuracion.branchoffice.read",
      icon: "document",
    },
    {
      id: "configuracion.model-tracker",
      label: "Rastreador/Catálogo de modelos Mongo",
      order: 0,
      pageId: "configuracion.model-tracker",
      path: "model-tracker",
      permission: "subject.configuracion.model-tracker.read",
      icon: "document",
    },
    {
      id: "configuracion.api-keys",
      label: "API keys",
      order: 1,
      pageId: "configuracion.api-keys",
      path: "api-keys",
      permission: "subject.configuracion.api-keys.read",
      icon: "document",
    },
    {
      id: "configuracion.epson-ticket-template",
      label: "Plantillas EPSON",
      order: 4,
      pageId: "configuracion.epson-ticket-template",
      path: "epson-ticket-template",
      permission: "subject.configuracion.epson-ticket-template.read",
      icon: "document",
    },
    {
      id: "configuracion.tags",
      label: "Etiquetas",
      order: 10,
      pageId: "configuracion.tags",
      path: "tags",
      permission: "subject.configuracion.tags.read",
      icon: "document",
    },
    {
      id: "configuracion.user-pin",
      label: "Pins de usuario",
      order: 60,
      pageId: "configuracion.user-pin",
      path: "user-pin",
      permission: "subject.configuracion.user-pin.read",
      icon: "document",
    },
    {
      id: "configuracion.debug-log",
      label: "Logs del Sistema",
      order: 99,
      pageId: "configuracion.debug-log",
      path: "debug-log",
      permission: "subject.configuracion.debug-log.read",
      icon: "document",
    }
    ],
});
