import {
  build_feature_shell_page,
  type KirletPageDecl,
} from "@opus-perpetuus/imperium-core-kit";

const API = "api://m/subject-configuracion";

export const configuration_pages: KirletPageDecl[] = [
  {
    id: "configuracion.configuration",
    path: "configuration",
    permission: "subject.configuracion.configuration.read",
    build: () =>
      build_feature_shell_page({
        id: "configuracion.configuration",
        owner: "subject-configuracion",
        title: "Parametros del sistema",
        props: {
          basePath: "configuration",
          idKey: "id",
          nameKey: "name",
          view: {
            title: "Parametros del sistema",
            subtitle: "Submenú de configuracion",
            pluralLabel: "parametros del sistema",
            singularLabel: "parametros del sistema",
            emptyTitle: "Sin registros",
            emptyDescription: "Migra desde Mongo o crea el primero",
          },
          data: {
            list: `${API}/configuration`,
            record: `${API}/configuration/:id`,
            create: { method: "POST", action: `${API}/configuration` },
            update: { method: "PATCH", action: `${API}/configuration/:id` },
            delete: { method: "DELETE", action: `${API}/configuration/:id` },
          },
          table: {
            columns: [
              { key: "name", label: "Nombre", sortable: true, priority: 1 },
              { key: "is_active", label: "Activo", sortable: true, priority: 2 },
              { key: "ref", label: "Ref", sortable: true, priority: 3 },
              { key: "is_system", label: "is system", sortable: true, priority: 3 },
              { key: "model_id", label: "model id", sortable: true, priority: 3 },
              { key: "module_id", label: "module id", sortable: true, priority: 3 },
              { key: "value", label: "value", sortable: true, priority: 3 },
              { key: "type", label: "type", sortable: true, priority: 3 },
              { key: "user_id", label: "user id", sortable: true, priority: 3 },
            ],
            fillHeight: true,
            serverQuery: true,
          },
          form: {
            fields: [
              { name: "name", component: "input-text", label: "Nombre", required: true },
              { name: "description", component: "input-textarea", label: "Descripción" },
              { name: "ref", component: "input-text", label: "Referencia (_ref)" },
              { name: "is_system", component: "input-checkbox", label: "is system" },
              { name: "model_id", component: "input-text", label: "model id" },
              { name: "module_id", component: "input-text", label: "module id" },
              { name: "value", component: "input-json", label: "value" },
              {
                name: "type",
                component: "input-datalist",
                label: "type",
                options: [
                  { value: "text", label: "Text" },
                  { value: "timer", label: "Timer" },
                  { value: "password", label: "Password" },
                  { value: "textarea", label: "Textarea" },
                  { value: "checkbox", label: "Checkbox" },
                  { value: "checkbox-group", label: "Checkbox-group" },
                  { value: "select", label: "Select" },
                  { value: "radio-buttons", label: "Radio-buttons" },
                  { value: "number", label: "Number" },
                  { value: "mask", label: "Mask" },
                  { value: "signature", label: "Signature" },
                  { value: "image", label: "Image" },
                  { value: "money", label: "Money" },
                  { value: "coordinates", label: "Coordinates" },
                  { value: "date-range", label: "Date-range" },
                  { value: "date", label: "Date" },
                  { value: "datetime", label: "Datetime" },
                  { value: "week", label: "Week" },
                  { value: "month", label: "Month" },
                  { value: "weekday", label: "Weekday" },
                  { value: "year", label: "Year" },
                  { value: "markdown", label: "Markdown" },
                  { value: "code-editor", label: "Code-editor" },
                  { value: "datalist", label: "Datalist" },
                  { value: "status", label: "Status" },
                  { value: "icon", label: "Icon" },
                  { value: "component", label: "Component" },
                  { value: "breadcrumb", label: "Breadcrumb" },
                  { value: "editor_html_pdf", label: "Editor_html_pdf" },
                  { value: "object", label: "Object" },
                  { value: "switch", label: "Switch" },
                  { value: "time", label: "Time" },
                  { value: "color", label: "Color" },
                  { value: "file", label: "File" },
                  { value: "choice", label: "Choice" },
                  { value: "radio-group", label: "Radio-group" },
                ],
              },
              { name: "user_id", component: "input-text", label: "user id" },
            ],
          },
        },
      }),
  },
];
